vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        post_image:
            uri_prefix: /image/post
            upload_destination: '%kernel.project_dir%/public/image/post'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    